# Generated by Django 5.2 on 2025-04-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPZ', models.CharField(max_length=8)),
                ('Znacka', models.CharField(max_length=64)),
                ('Model', models.CharField(max_length=64)),
                ('Motor', models.CharField(max_length=64)),
                ('Prevodovka', models.CharField(max_length=64)),
                ('Palivo', models.CharField(max_length=64)),
                ('Rok_vyroby', models.CharField(max_length=64)),
                ('Kategorie', models.CharField(max_length=64)),
                ('Vykon', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Den_pujceni', models.DateField()),
                ('Den_vraceni', models.DateField()),
                ('penize_za_den', models.IntegerField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujcky', to='pujcovna.auto')),
            ],
        ),
    ]
