# Generated by Django 5.2 on 2025-05-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujcovna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='Prevodovka',
        ),
        migrations.AddField(
            model_name='auto',
            name='Prevovodovka',
            field=models.CharField(default=1251, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='Kategorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Motor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Palivo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Rok_vyroby',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='SPZ',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Vykon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Znacka',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pujcka',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pujcovna.auto'),
        ),
        migrations.AlterField(
            model_name='pujcka',
            name='penize_za_den',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
