# Generated by Django 5.2 on 2025-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujcovna', '0002_remove_auto_prevodovka_auto_prevovodovka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='obrazky/'),
        ),
    ]
